version: '3.4'
services:
  busfeedback:
    image: ${DOCKER_REGISTRY-}busfeedback
    container_name: busfeedback
    ports:
      - 5214:80
    build:
      context: .
      dockerfile: BusFeedback/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    networks:
      - postgres
    depends_on:
      - postgres

  busreservation:
    image: ${DOCKER_REGISTRY-}busreservation
    container_name: busreservation
    ports:
      - 5213:80
    build:
      context: .
      dockerfile: BusReservation/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    networks:
      - postgres
    depends_on:
      - postgres

  busroutes:
    image: ${DOCKER_REGISTRY-}busroutes
    container_name: busroutes
    ports:
      - 5216:80
    build:
      context: .
      dockerfile: BusRoute/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    networks:
      - postgres
    depends_on:
      - postgres

  user:
    image: ${DOCKER_REGISTRY-}user
    container_name: user
    ports:
      - 5217:80
    build:
      context: .
      dockerfile: User/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    networks:
      - postgres
    depends_on:
      - postgres
      - busreservation
      - busroutes
      - busfeedback
      - weather

  weather:
    image: ${DOCKER_REGISTRY-}weather
    container_name: weather
    ports:
      - 5218:80
    build:
      context: .
      dockerfile: Weather/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"


  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: kosovatour
      POSTGRES_PASSWORD: kosovatour
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: kosova@gmail.com
      PGADMIN_DEFAULT_PASSWORD: kosovatour
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 8080:80
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
    driver: local
  pgadmin:
    driver: local